updated workflow file

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -37,9 +37,11 @@ jobs:
 
     - name: Run Pytest
       run: |
-        if [ -d "tests" ]; then
-          python -m pytest --cov=app/commands/arithmetic.py  --cov-report=term-missing --cov-fail-under=50 tests/
-        else
-          echo "Error: 'tests/' directory not found"
-          exit 1
-        fi
+          if [[ -f "app/commands/arithmetic.py" ]]; then
+            python -m pytest --cov=app/commands/arithmetic.py --cov-report=term-missing --cov-fail-under=50 tests/
+          else
+            echo "Error: 'app/commands/arithmetic.py' file not found"
+            exit 1
+          fi
+      shell: bash
+      
